//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gogol
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksPhoto
    {
        public int Id { get; set; }
        public Nullable<int> BOOK_ID { get; set; }
        public byte[] PHOTO { get; set; }
    
        public virtual Book Book { get; set; }
    }
}
